id = "macrottie.exceptions"
name = "exceptions"
description = "Simple mod to allow friends to join even when your lobby is full."
version = "1.0.0"
homepage = "https://github.com/mmccall0813/exceptions"
author = "macrottie"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./macrottie.exceptions/macrottie.exceptions.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"